### ISSUE TITLE
website get stuck on infinite loading on old browsers

### ISSUE THREAD

**Issue by kevinoliveira** [onilton/deck-covid19#2]
![image](https://user-images.githubusercontent.com/14365975/81452020-2ca12b00-915c-11ea-947b-3498419493d3.png)

**Comment by kevinoliveira** [comment]
the problem happens here, https://github.com/onilton/deck-covid19/blob/master/index.js#L234 on some browsers `Object.fromEntries` is not implement, especially on old versions, to solve this you can use this polyfill https://github.com/es-shims/Object.fromEntries

**Comment by onilton** [comment]
What is your browser?

**Comment by kevinoliveira** [comment]
Chrome 72

**Comment by onilton** [comment]
Ok. Was the message update your browser shown to you ? (It is red and has a button leading to http://outdatedbrowser.com/ )

**Comment by kevinoliveira** [comment]
No sign of any message.

**Comment by onilton** [comment]
@kevinoliveira Hi, can you try one more time now? 

https://onilton.github.io/deck-covid19/

**Comment by kevinoliveira** [comment]
Awesome, works now
![image](https://user-images.githubusercontent.com/14365975/81984194-d5db9b80-960a-11ea-9795-73c508338652.png)

**Comment by onilton** [comment]
Ok. Thanks for your report! The oldest chrome we support is 79. Did you manage to see the site/tool working? 

Anything else, just open an issue :)

**Comment by onilton** [comment]
Fixed in https://github.com/onilton/deck-covid19/commit/25eb3b6b6bde5d0942727691a52bbf9e804c15cf
